export const title = "My skillset includes 🛠️";
export const skills = [
  "Semantic & accessible HTML",
  "Responsive Web Design",
  "Teamwork",
  "Markdown",
  "Immutability",
  "CSS BEM convention",
  "CSS grid",
  "css Flexbox",
  "Styled-Components",
  "react router",
  "redux saga",
  "redux(Toolkit)",
  "react hooks",
  "error handling",
  "working with API (fetch, axios)",
  "Javascript: ES6+",
  "Promises, Async/Await",
  "Github pull requests & review",
  "Trello",
  "Scrum",
  "NPM",
  "react",
  "git",
];
