export const title = "My skillset includes 🛠️";
export const skills = [
    "Semantic & accessible HTML",
    "Responsive Web Design",
    "Teamwork",
    "Markdown",
    "Immutability",
    "CSS BEM convention",
    "CSS grid",
    "CSS Flexbox",
    "Styled-Components",
    "React router",
    "Redux saga",
    "Redux(Toolkit)",
    "React hooks",
    "Error handling",
    "Working with API (fetch, axios)",
    "Javascript: ES6+",
    "Promises, Async/Await",
    "Github pull requests & review",
    "Trello",
    "Scrum",
    "NPM",
    "React",
    "Git",
    "Basic node.js",
    "File System module",
    "Path module",
    "Chokidar",
    "Node Proccess",
    "Crypto module",
    "Buffers / Streams",
    "Event Emitter",
    "HTML module",
    "Creating API",
];
